### ISSUE TITLE
Segmentation fault 0x000000000501845c in L_P11UTIL_single_load ()

### ISSUE THREAD

**Issue by fjbermudez** [opendnssec/SoftHSMv2#264]
Hi, 
I'm trying to use softHSM via pkcs11 and I'm hitting a crash when I call C_Initialized. 
I tried loading the library and using the function pointer and statically linking with the same result. 

Program received signal SIGSEGV, Segmentation fault.
0x000000000501845c in L_P11UTIL_single_load ()
(gdb) where
#0  0x000000000501845c in L_P11UTIL_single_load ()
#1  0x000000000500cfa4 in p11lib_PKCS11_IMPL ()
#2  0x000000000500d14a in C_Initialize ()
..
(gdb) p initArgs
$1 =  {CreateMutex = 0x0, DestroyMutex = 0x0, LockMutex = 0x0, UnlockMutex = 0x0, 
  flags = 2, pReserved = 0x0}

I tried to build the library with debug symbols to step into the code but I'm hitting a compiler error that I don't see where  OPENSSL_FIPS is been defined. I tried ./configure --disable-fips with the same outcome. 
I looking for some pointers on getting it to compile or What could be causing the segfault. 

 g++ -DHAVE_CONFIG_H -I. -I../../.. -I./../common -I./../cryptoki_compat -I./../data_mgr -I./.. -I/usr/local/include -g -O2 -Wall -Wextra -std=c++11 -fvisibility=hidden -MT OSSLRSAKeyPair.lo -MD -MP -MF .deps/OSSLRSAKeyPair.Tpo -c OSSLRSAKeyPair.cpp -o OSSLRSAKeyPair.o >/dev/null 2>&1

OSSLRSAPrivateKey.cpp: In member function 'void OSSLRSAPrivateKey::createOSSLKey()':
OSSLRSAPrivateKey.cpp:296:45: error: 'FIPS_rsa_pkcs1_ssleay' was not declared in this scope
   RSA_set_method(rsa, FIPS_rsa_pkcs1_ssleay());
                                             ^
make[5]: *** [OSSLRSAPrivateKey.lo] Error 1
make[5]: *** Waiting for unfinished jobs....
OSSLRSAPublicKey.cpp: In member function 'void OSSLRSAPublicKey::createOSSLKey()':
OSSLRSAPublicKey.cpp:137:45: error: 'FIPS_rsa_pkcs1_ssleay' was not declared in this scope
   RSA_set_method(rsa, FIPS_rsa_pkcs1_ssleay());

**Comment by fjbermudez** [comment]
Turns out that the problem is due to a secondary library has a wrapper implementation of PKCS11 and it is crashing because there is a conflict with the loaded softHSM library. 
Closing this issue.
