### ISSUE TITLE
segfault on C_Sign

### ISSUE THREAD

**Issue by akafazov** [opendnssec/SoftHSMv2#625]
I am getting Segmentation fault (core dumped) when using pkcs11js v1.1.2 with fabric-network v2.2.2 and SoftHSM2 v2.6.1 on alpine. The SoftHSM seems to work correctly with fabric-ca-client, but with Node I am getting the segfault. I managed to trace it to

pkcs11.C_Sign call at bccsp_pkcs11.js._pkcs11Sign(pkcs11, pkcs11Session, key, digest)

The segfault seems to happen in the SoftHSM2 lib.

I have tried compiling SoftHSM2 with the openssl headers of Node and also different version of fabric-network and SoftHSM2 without success.

**Comment by rijswijk** [comment]
I'm afraid I really can't help with Node.JS and PKCS #11, any other community members have an idea?

**Comment by akafazov** [comment]
Hi @rijswijk, here is a Dockerimage with tests that reproduce the issue, with and without NodeJS - https://github.com/akafazov/SoftHSM2FabricNodeSdk

**Comment by rijswijk** [comment]
Could you make a stack dump with `gdb` instead? That will help pinpoint where the error occurs. I'm afraid we have very little time for development at the moment, but maybe a quick stack dump will help pinpoint what is happening.

**Comment by akafazov** [comment]
Here are the tracetraces of both test scripts

```
warning: Can't read pathname for load map: No error information.
Core was generated by `node pkcs11test.js'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fdc41ab6494 in BN_clear_free () from /lib/libcrypto.so.1.1
[Current thread is 1 (LWP 100)]
(gdb) backtrace
#0  0x00007fdc41ab6494 in BN_clear_free () from /lib/libcrypto.so.1.1
#1  0x00007fdc41ab7671 in BN_MONT_CTX_free () from /lib/libcrypto.so.1.1
#2  0x00007fdc3ee23617 in ?? () from /lib/libcrypto.so.43
#3  0x00007fdc41b812b4 in RSA_free () from /lib/libcrypto.so.1.1
#4  0x00007fdc3ef4c2bd in OSSLRSAPrivateKey::~OSSLRSAPrivateKey (this=0x556d2c3ad700, __in_chrg=<optimized out>) at OSSLRSAPrivateKey.cpp:61
#5  OSSLRSAPrivateKey::~OSSLRSAPrivateKey (this=0x556d2c3ad700, __in_chrg=<optimized out>) at OSSLRSAPrivateKey.cpp:62
#6  0x00007fdc3ef64682 in Session::resetOp (this=this@entry=0x556d2c3ab760) at Session.cpp:213
#7  0x00007fdc3ef0c077 in AsymSignFinal (pulSignatureLen=0x7ffec469cae8, pSignature=0x556d2c3af1a0 "", session=0x556d2c3ab760) at SoftHSM.cpp:4758
#8  SoftHSM::C_SignFinal (this=<optimized out>, hSession=<optimized out>, pSignature=0x556d2c3af1a0 "", pulSignatureLen=0x7ffec469cae8) at SoftHSM.cpp:4794
#9  0x00007fdc3eeef293 in C_SignFinal (hSession=1, pSignature=0x556d2c3af1a0 "", pulSignatureLen=0x7ffec469cae8) at main.cpp:812
#10 0x00007fdc3efd77c1 in crypto_final(unsigned long (*)(unsigned long, unsigned char*, unsigned long*), unsigned long, std::shared_ptr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >) () from /webapp/node_modules/pkcs11js/build/Release/pkcs11.node
#11 0x00007fdc3efd7c12 in PKCS11::C_SignFinal(unsigned long, std::shared_ptr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >) ()
   from /webapp/node_modules/pkcs11js/build/Release/pkcs11.node
#12 0x00007fdc3efed4bd in WPKCS11::C_SignFinal(Nan::FunctionCallbackInfo<v8::Value> const&) () from /webapp/node_modules/pkcs11js/build/Release/pkcs11.node
#13 0x00007fdc3efdd93f in Nan::imp::FunctionCallbackWrapper(v8::FunctionCallbackInfo<v8::Value> const&) () from /webapp/node_modules/pkcs11js/build/Release/pkcs11.node
#14 0x0000556d2aa186d8 in v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) ()
#15 0x0000556d2aa18a67 in ?? ()
#16 0x0000556d2aa19060 in ?? ()
```


```
warning: Can't read pathname for load map: No error information.
Core was generated by `node nodehsmtest.js'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f21c945b6ac in ?? () from /lib/libcrypto.so.43
[Current thread is 1 (LWP 107)]
(gdb) backtrace
#0  0x00007f21c945b6ac in ?? () from /lib/libcrypto.so.43
#1  0x00007f21c945b1e5 in EC_KEY_get_key_method_data () from /lib/libcrypto.so.43
#2  0x00007f21c94627de in ?? () from /lib/libcrypto.so.43
#3  0x00007f21c9462834 in ECDSA_set_method () from /lib/libcrypto.so.43
#4  0x00007f21c95b630e in OSSLECDSA::sign (this=<optimized out>, mechanism=AsymMech::ECDSA, signature=..., dataToSign=..., privateKey=0x55e92ab45620) at OSSLECDSA.cpp:89
#5  OSSLECDSA::sign (this=<optimized out>, privateKey=0x55e92ab45620, dataToSign=..., signature=..., mechanism=<optimized out>) at OSSLECDSA.cpp:52
#6  0x00007f21c957eaca in AsymSign (pulSignatureLen=0x7ffe511891c8, pSignature=0x55e92ab458e0 "", ulDataLen=32, pData=<optimized out>, session=0x55e92ac69b60) at SoftHSM.cpp:4554
#7  SoftHSM::C_Sign (this=<optimized out>, hSession=<optimized out>, pData=<optimized out>, ulDataLen=32, pSignature=0x55e92ab458e0 "", pulSignatureLen=0x7ffe511891c8) at SoftHSM.cpp:4594
#8  0x00007f21c9562223 in C_Sign (hSession=1, pData=0x55e92aceef00 "\324\071_\006ش\327F\273\234\030*;\326ן\036\267\003\373\373\nb=}\232\215\067\071\213a\275", ulDataLen=32, 
    pSignature=0x55e92ab458e0 "", pulSignatureLen=0x7ffe511891c8) at main.cpp:782
#9  0x00007f21c9649d8b in crypto_update(unsigned long (*)(unsigned long, unsigned char*, unsigned long, unsigned char*, unsigned long*), unsigned long, std::shared_ptr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::shared_ptr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >) ()
   from /webapp/node_modules/pkcs11js/build/Release/pkcs11.node
#10 0x00007f21c964a4ef in PKCS11::C_Sign(unsigned long, std::shared_ptr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::shared_ptr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >) () from /webapp/node_modules/pkcs11js/build/Release/pkcs11.node
#11 0x00007f21c965f697 in WPKCS11::C_Sign(Nan::FunctionCallbackInfo<v8::Value> const&) () from /webapp/node_modules/pkcs11js/build/Release/pkcs11.node
#12 0x00007f21c965093f in Nan::imp::FunctionCallbackWrapper(v8::FunctionCallbackInfo<v8::Value> const&) () from /webapp/node_modules/pkcs11js/build/Release/pkcs11.node
#13 0x000055e92947e6d8 in v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) ()
#14 0x000055e92947ea67 in ?? ()
#15 0x000055e92947f060 in ?? ()
```

**Comment by rijswijk** [comment]
OK, so the segmentation fault is not actually happening in the SoftHSM dynamic library but in OpenSSL.

In the first stacktrace, the fault occurs when the destructor of an internal SoftHSM class attempts to free an RSA private key object. In the second stacktrace, the fault occurs when manipulating an ECDSA key.

This does not look like an issue with SoftHSM to me, rather, one of the possible causes could be that SoftHSM was linked against another OpenSSL library than Node.JS (so not different headers, but a different shared library), and there is an alignment problem (structure packing). If Node.JS loads OpenSSL first, then the dynamic linker will resolve the symbols SoftHSM refers to from that binary, causing problems.

This is, unfortunately, really beyond the scope of the SoftHSM project to solve, you could attempt to build SoftHSM against the same OpenSSL library as Node.JS to see if that solves your problem.

**Comment by dengert** [comment]
Have a look at the  ld options -b and -z. You may need to force a module to be self contained, so that each module can use a different version of libcrypto then other modules or the main application. 

PAM has this problem, as many different modules are used. 

First find which modules are using /lib/libcrypto.so.43 and /lib/libcrypto.so.1.1 with the ldd.

**Comment by akafazov** [comment]
Thanks both of you, the cause was exactly as you described it - a library conflict. Turns out I have been installing libressl, an openssl fork, which was causing the issue. After removing it and installing openssl the segfault is gone.
